version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/a9n4a1k0
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t  tempimage:latest .
      - docker tag tempimage:latest public.ecr.aws/a9n4a1k0/flask-repo:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/a9n4a1k0/flask-repo:latest